name: 'DroneCI Build Trigger'
description: 'Trigger Drone CI build via API'
branding:
  icon: 'settings'
  color: blue
inputs:
  droneApiUrl:
    description: 'URL of API for interacting with the Drone server. Example: http://localhost:8080/api'
    required: true
    default: 'http://drone.recursive-escalator.io/api'
  droneApiToken:
    description: 'Drone API Personal Token'
    required: true

outputs:
  time: # output will be available to future steps
    description: 'The message to output'
runs:
  using: 'node12'
  main: 'dist/index.js'
